INSERT INTO AUTHENTICATIONGROUP(ID, USER_NAME, AUTH_GROUP) VALUES(1, 'TEST', 'USER');
INSERT INTO AUTHENTICATIONGROUP(ID, USER_NAME, AUTH_GROUP) VALUES(2, 'LIBRARIAN', 'LIBRARIAN');

INSERT INTO USER(ID, USER_NAME, PASSWORD, FULL_NAME) VALUES(1, 'test', '$2a$11$Bd/BGzf7iJyyXRXi7ush8Oy.Gsw2zFiQJAijIhmeQ5BOt3UL7MBB2', 'user');
INSERT INTO USER(ID, USER_NAME, PASSWORD, FULL_NAME) VALUES(2, 'lib', '$2a$11$Bd/BGzf7iJyyXRXi7ush8Oy.Gsw2zFiQJAijIhmeQ5BOt3UL7MBB2', 'librarian');
INSERT INTO USER(ID, USER_NAME, PASSWORD, FULL_NAME) VALUES(3, 'test01', '$2a$11$Bd/BGzf7iJyyXRXi7ush8Oy.Gsw2zFiQJAijIhmeQ5BOt3UL7MBB2', 'user01');

INSERT INTO BOOK(ID, TITLE, AMOUNT) VALUES(1, 'Amazing Book', 2);
INSERT INTO BOOK(ID, TITLE, AMOUNT) VALUES(2, 'Less Amazing Book', 3);
INSERT INTO BOOK(ID, TITLE, AMOUNT) VALUES(3, 'No Book', 0);

INSERT INTO BORROW(ID, START_DATE, END_DATE, BOOK_ID) VALUES(1, '2020-01-01', '2020-02-01', 1);
INSERT INTO BORROW(ID, START_DATE, END_DATE, BOOK_ID) VALUES(2, '2020-01-01', '2020-02-01', 2);
INSERT INTO BORROW(ID, START_DATE, END_DATE, BOOK_ID) VALUES(3, '2020-01-01', '2020-02-01', 1);

INSERT INTO USER_BORROW(USER_ID, BORROWS_ID) VALUES(1, 1);
INSERT INTO USER_BORROW(USER_ID, BORROWS_ID) VALUES(1, 2);
INSERT INTO USER_BORROW(USER_ID, BORROWS_ID) VALUES(3, 3);